# python -c 'import crypt; print crypt.crypt("password", "$1$changeme$")'
- name: create user
  user: name='{{item.name}}'
        shell='{{item.shell}}'
        update_password=on_create
        uid='{{item.uid}}'
  register: user_creation

- name: allow user to have sudo
  user: name='{{item.name}}'
        groups=wheel
        append=yes
  when: "{{item.allow_sudo}} == true"

- file: state=directory
        path=/home/{{item.name}}/.ssh/
        mode=0700 owner={{item.name}} group={{item.name}}

- name: copy user's SSH key
  copy: src={{item.name}}.keys
        dest=/home/{{item.name}}/.ssh/authorized_keys
        owner={{item.name}}
        group={{item.name}}
        mode=0700

